[project]
name = "simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "chiahsiangshyu@tamu.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
]

[project.scripts]
simulation = "simulation:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
